/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Loading_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Loading_Screen
     */
    public Loading_Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Loading...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0%");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddNewBookIcons/66982lms.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));

        progress.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 640, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       Loading_Screen sp = new Loading_Screen();
       sp.setVisible(true);
        
      try{
            
                for(int i=0;i<=100;i++){
                Thread.sleep(100);
                sp.jLabel3.setText(i +"%");
                
                if(i==10){
                    sp.jLabel2.setText("Turning On Modules...");
                }
                
                if(i==20){
                    sp.jLabel2.setText("Turning On Modules...");
                }
                
                if(i==20){
                    sp.jLabel2.setText("Loading Modules...");
                }
                
                if(i==50){
                    sp.jLabel2.setText("Connecting To Database...");
                }
                
                if(i==70){
                    sp.jLabel2.setText("Connected...");
                }
                
                if(i==80){
                    sp.jLabel2.setText("Launching Application...");
                }
                
                sp.progress.setValue(i);
               
                
            }
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, e);
    }
      
       Login if2_a1 = new Login();
       if2_a1.show();
       sp.dispose();
        
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
